### ISSUE TITLE
errors with latest quicklisp

### ISSUE THREAD

**Issue by nightshade427** [orthecreedence/carrier#11]
carrier errors on latest quicklisp for april due to incompatability with new fast-http

**Comment by orthecreedence** [comment]
What's the error you're getting? Hard for me to know if I have the versions you're using so it might be a pain to reproduce if I can't pinpoint it. Thanks!

**Comment by nightshade427** [comment]
Im getting proc parse errors from fast-http. 

Looks like he recently siwtched to proc-parse but its giving errors for some requests im making ```proc-parse:match-failed```

If I switch to tag 92f4627 in fast-http (pre-proc-parse) I dont get any errors.

Will try and track down why fast-http and proc-parse is throwing match-failed on the response of some of my requests. Will let you know what I find out.

**Comment by nightshade427** [comment]
Okay tracked this down. The new proc-parse stuff expects the data to be good all in one shot. Here is the reponses from carrier when interacting with fast-http:

```lisp
carrier data: "H"                                                                                                       
carrier data: "TTP/1.1 200 OK"
```

That is what carrier is sending to fast-http, notice the first call to fast-http is only "H" then another call with "TTP/1.1 200 OK". The pre-proc-parser used to take this in as a stream and process each character and a time building up. The new fast-http with proc-paraser sets expectations on each call to it to be valid and no longer lets it build up like that, so it throws error when it only gets "H".

If that makes sense.

**Comment by fukamachi** [comment]
I've rewritten fast-http with proc-parse and it found out to be a bug of proc-parse.
I've fixed it in the latest proc-parse.
Could you please retry with it?

https://github.com/fukamachi/proc-parse

**Comment by nightshade427** [comment]
Looks great! Thanks!
