### ISSUE TITLE
HTTP request returning nil 

### ISSUE THREAD

**Issue by fiddlerwoaroof** [orthecreedence/carrier#14]
Running this:

```
(cl-async:with-event-loop ()
  (blackbird:attach (carrier:request "http://api.ipify.org")
                    (lambda (r c h)
                      (format t "~&data: ~a~%code: ~a~%headers: ~s"
                              r c
                              (alexandria:hash-table-alist h)))))
```

produces the output:

```
data: NIL
code: 200
headers: (("via" . "1.1 vegur") ("content-length" . 12) ("date" . "Mon, 29 Aug 2016 18:54:32 GMT") ("content-type" . "text/plain")
          ("connection" . "keep-alive") ("server" . "Cowboy"))
0
```

Rather than printing `data: <my ip address>`.  It looks to me like the body of the http request isn't being handled correctly.

**Comment by orthecreedence** [comment]
The body is not returned by default (`Carrier` is built with streaming in mind). See the [`return-body` keyword](https://github.com/orthecreedence/carrier#request-function) in the docs.

**Comment by orthecreedence** [comment]
Oh, just realized the parameter was named incorrectly in the docs (was `store-body`). That would have been confusing. Fixed!

**Comment by fiddlerwoaroof** [comment]
Thanks, I guess I didn't read the docs carefully enough.  Also, I probably should open another ticket, but is it possible to stream the request body (for, say, posting a large file?)

**Comment by orthecreedence** [comment]
Actually, no there's not a way to stream the request body. Hasn't come up yet =]. Feel free to open a new issue for that.
