### ISSUE TITLE
ssl causes faults on sbcl

### ISSUE THREAD

**Issue by nightshade427** [orthecreedence/carrier#5]
There seems to be an issue where if you ssl uris with carrier and lastest cl-async it cases memory faults and other issues.

This works:

``` lisp
(as:with-event-loop ()                                                                                                                                                   
           (asf:alet ((result (carrier:request "http://www.apple.com/" :return-body t)))                                                                                          
             (format t "result: ~s" result))) 
```

This one explodes:

``` lisp
(as:with-event-loop ()                                                                                                                                                   
           (asf:alet ((result (carrier:request "https://www.apple.com/" :return-body t)))                                                                                          
             (format t "result: ~s" result)))
```

**Comment by orthecreedence** [comment]
Hi Nick, sorry for the delay, been trying to improve the error reporting of cl-async to track this one down (see https://github.com/orthecreedence/cl-async/issues/108). Looks like including cl+ssl with cl-async-ssl creates a memory fault in sbcl. Good catch! I am going to pick away at this today, although we're still doing some holiday stuff over here so I may not finish today.

**Comment by orthecreedence** [comment]
I think this is fixed. Please pull cl-async (in fact, pull cl-libuv, carrier, and blackbird while you're at it, I want to make sure you're all up to date).

Note that the way this was fixed may cause problems when trying to use cl+ssl with cl-async-ssl loaded, but I haven't tested this and I'm not sure if there's a way to make the two play nicely.
